const fs = require('fs');

const rawData = [
    { id: "ZC599", name: "Amr Nasr", email: "amr.nasr@zaincash.iq", role: "Admin" },
    { id: "ZC000", name: "Amr Nasr", email: "amr.nasr@zaincash.iq", role: "Admin" },
    { id: "ZC700", name: "Kadhim Mohammed Safi", email: "kadhim.mohammed@zaincash.iq", role: "Inbound" },
    { id: "ZC476", name: "Mustafa Khudhaier Abbas", email: "mustafa.khudher@zaincash.iq", role: "Inbound" },
    { id: "ZC552", name: "Aso Sarbest Nathmi", email: "aso.sarbast@zaincash.iq", role: "Inbound" },
    { id: "ZC733", name: "Tara faris fouad", email: "tara.faris@zaincash.iq", role: "Inbound" },
    { id: "ZC580", name: "Hayman Omed Mohammed", email: "hemn.omed@zaincash.iq", role: "Inbound" },
    { id: "ZC624", name: "Ruqaya Nadhim", email: "ruqaya.nadhum@zaincash.iq", role: "Inbound" },
    { id: "ZC739", name: "Ahmed Khalil Fatah", email: "ahmed.fatah@zaincash.iq", role: "Inbound" },
    { id: "ZC737", name: "Dheyaa Mohammed Khudhair", email: "dhyaa.mohammed@zaincash.iq", role: "Inbound" },
    { id: "ZC639", name: "Mustafa Abdulsahib Najim", email: "mustafa.abdulsahib@zaincash.iq", role: "Inbound" },
    { id: "ZC500", name: "Omar Fadhil Sleman", email: "omar.fadhil@zaincash.iq", role: "Inbound" },
    { id: "ZC291", name: "Ali Mohammed Ameen", email: "ali.ameen@zaincash.iq", role: "Inbound" },
    { id: "ZC672", name: "Mustafa Ahmed Khadir", email: "mustafa.ahmed@zaincash.iq", role: "Inbound" },
    { id: "ZC627", name: "Abdullah Loay", email: "abdullah.loay@zaincash.iq", role: "Inbound" },
    { id: "ZC735", name: "MOHAMMED RAGHEED HAMID", email: "mohammed.raghed@zaincash.iq", role: "Inbound" },
    { id: "ZC743", name: "Ali Shakir Eand", email: "ali.shakir@zaincash.iq", role: "Inbound" },
    { id: "ZC311", name: "Ahmed AbdulRazaq Hameed", email: "ahmed.abdulrazaq@zaincash.iq", role: "Inbound" },
    { id: "ZC703", name: "Houthaifa Waleed Razuki", email: "houthaifa.waleed@zaincash.iq", role: "Inbound" },
    { id: "ZC657", name: "Maytham Ali Mohammed", email: "maytham.ali@zaincash.iq", role: "Inbound" },
    { id: "ZC738", name: "Hazem Emad Hamdi", email: "hazem.emad@zaincash.iq", role: "Inbound" },
    { id: "ZC655", name: "Muhammad Zaman", email: "mohammed.zaman@zaincash.iq", role: "Inbound" },
    { id: "ZC683", name: "Ali Ryadh Hadi", email: "ali.riyadh@zaincash.iq", role: "Inbound" },
    { id: "ZC681", name: "Alaa Hussein Ali", email: "alaa.hussein@zaincash.iq", role: "Inbound" },
    { id: "ZC740", name: "Ali Wisam Abdulsattar", email: "ali.wisam@zaincash.iq", role: "Inbound" },
    { id: "ZC332", name: "Monier Yasir Monier", email: "monier.yasir@zaincash.iq", role: "Inbound" },
    { id: "ZC579", name: "Ahmed Haitham Kadhim", email: "ahmad.haitham@zaincash.iq", role: "Inbound" },
    { id: "ZC416", name: "Nooralhuda Ali Hamza", email: "nooralhuda.ali@zaincash.iq", role: "Inbound" },
    { id: "ZC676", name: "Hamza Dhiaa Mubder", email: "hamza.dhiaa@zaincash.iq", role: "Inbound" },
    { id: "ZC741", name: "Montzer Muneer Taha", email: "montadhar.monier@zaincash.iq", role: "Inbound" },
    { id: "ZC501", name: "Hussein Mohammed Ibrahim", email: "hussein.mohammed@zaincash.iq", role: "Inbound" },
    { id: "ZC578", name: "Maryam Thaer Talib", email: "maryam.thaer@zaincash.iq", role: "Inbound" },
    { id: "ZC577", name: "Hasan Ammar sabir", email: "hasan.ammar@zaincash.iq", role: "Inbound" },
    { id: "ZC194", name: "Haneen Ahmed Zaki", email: "haneen.ahmed@zaincash.iq", role: "Inbound" },
    { id: "ZC673", name: "Forqan Zuhaer Mohamed", email: "forqan.zuhaer@zaincash.iq", role: "Inbound" },
    { id: "ZC706", name: "Mustafa laith sophi", email: "mustafa.laith@zaincash.iq", role: "Inbound" },
    { id: "ZC532", name: "Maryam Tariq Jassam", email: "maryam.tariq@zaincash.iq", role: "Inbound" },
    { id: "ZC744", name: "Abdullah Faris Barghash", email: "abdullah.faris@zaincash.iq", role: "Inbound" },
    { id: "ZC489", name: "Sarah Ahmed Abd", email: "sarah.ahmed@zaincash.iq", role: "Inbound" },
    { id: "ZC485", name: "Ahmed Saad Abdulhadi", email: "ahmad.saad@zaincash.iq", role: "Inbound" },
    { id: "ZC366", name: "Sajjad Mahdi", email: "sajad.mahdi@zaincash.iq", role: "Inbound" },
    { id: "ZC434", name: "Aya Ali Hussien", email: "aya.ali@zaincash.iq", role: "Inbound" },
    { id: "ZC224", name: "Ali Sabeh Jassim", email: "ali.sabeeh@zaincash.iq", role: "Inbound" },
    { id: "ZC473", name: "Zainab Saad faeq", email: "zainab.saad@zaincash.iq", role: "Inbound" },
    { id: "ZC742", name: "Rahma Dored Jumaa", email: "rahma.duraid@zaincash.iq", role: "Inbound" },
    { id: "ZC625", name: "Ahmed Mohammed Khalil", email: "ahmed.khalil@zaincash.iq", role: "Inbound" },
    { id: "ZC609", name: "Ali Mohammed Sallal", email: "ali.mohammed@zaincash.iq", role: "Inbound" },
    { id: "ZC363", name: "Mohammed Asaad", email: "mohammed.asaad@zaincash.iq", role: "Inbound" },
    { id: "ZC582", name: "Maryam Ahmed Younis", email: "maryam.younis@zaincash.iq", role: "Inbound" },
    { id: "ZC471", name: "Dalia Salah Tayah", email: "dalia.salah@zaincash.iq", role: "Inbound" },
    { id: "ZC480", name: "Abdullah Abdulrahman Wahib", email: "abdullah.abdalrhman@zaincash.iq", role: "Inbound" },
    { id: "ZC702", name: "Abdullah Majid Hameed.", email: "abdullah.majid@zaincash.iq", role: "Inbound" },
    { id: "ZC646", name: "Yassir Khalil Qahtan", email: "yassir.khalil@zaincash.iq", role: "Inbound" },
    { id: "ZC315", name: "Mustafa Muwafaq Mohammedali", email: "mustafa.muwafaq@zaincash.iq", role: "Inbound" },
    { id: "ZC576", name: "Zaid Ahmed abbas", email: "zaid.ahmed@zaincash.iq", role: "Inbound" },
    { id: "ZC755", name: "Ibrahim Khalil Samir", email: "ibrahim.khalil@zaincash.iq", role: "Inbound" },
    { id: "ZC565", name: "Mohammed Waleed Mohammed", email: "mohammed.waleed@zaincash.iq", role: "Inbound" },
    { id: "ZC734", name: "Ali Abbas Rahman", email: "ali.abbas@zaincash.iq", role: "Inbound" },
    { id: "ZC643", name: "Mohammedalbaqir Haider Hussein", email: "mohammed.albaqer@zaincash.iq", role: "Inbound" },
    { id: "ZC758", name: "Nabaa Ali Mohhamed", email: "nabaa.ali@zaincash.iq", role: "Inbound" },
    { id: "ZC470", name: "Yaqeen Abdulkhdhur Hasan", email: "yakeen.abdulkhudhur@zaincash.iq", role: "Inbound" },
    { id: "ZC482", name: "Zainab Haider Jaffar", email: "zainab.haider@zaincash.iq", role: "Inbound" },
    { id: "ZC272", name: "Hasan Reyad Jabbar", email: "hassan.reyad@zaincash.iq", role: "Inbound" },
    { id: "ZC757", name: "Amna Dheyaa Hasan", email: "amna.dheyaa@zaincash.iq", role: "Inbound" },
    { id: "ZC745", name: "Abdul Razaq Haitham Mohsen", email: "abdulrazaq.haitham@zaincash.iq", role: "Inbound" },
    { id: "ZC481", name: "Yusor Raied Ismail", email: "yusor.raed@zaincash.iq", role: "Inbound" },
    { id: "ZC699", name: "Ameen saad nasef", email: "ameen.saad@zaincash.iq", role: "Inbound" },
    { id: "ZC262", name: "Sadoon Muhsin", email: "sadoon.mohsoun@zaincash.iq", role: "Inbound" }
];

const dbPath = 'C:/Users/kaka/Downloads/Test/db.json';
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
db.users = rawData;
fs.writeFileSync(dbPath, JSON.stringify(db, null, 4), 'utf8');
console.log('Successfully updated db.json with ' + rawData.length + ' users!');
